name: "🚀 Novo Projeto de Infraestrutura AWS"
description: "Preencha para gerar um novo repositório a partir deste template"
title: "Template para Infraestrutura AWS - Novo Projeto"
labels: ["template-bot"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por iniciar um novo projeto! Preencha os campos abaixo.
  - type: input
    id: nome_repo
    attributes:
      label: "Qual o nome do novo repositório?"
      description: "Use apenas letras minúsculas e hífens e inicie com o nome do projeto(ex: projeto-aws-infra-sqs)"
      placeholder: "nome-do-seu-repo"
    validations:
      required: true