name: "[DEV] deploy"

on: 
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      project_name: "rocket-project"
      aws-assume-role-arn: "arn:aws:iam::<id_aws>:role/<role_name>"
      aws-region: "sa-east-1"
